// A beginner-friendly film glossary. cat is one of the CATEGORIES below.
export const CATEGORIES = ['Camera', 'Lighting', 'Sound', 'Script', 'Editing', 'Crew', 'Production']

export const GLOSSARY = [
  // ----- Camera -----
  { term: 'Aperture', cat: 'Camera', def: 'The opening in a lens that lets light in. A small f-number like f/1.8 means a wide opening: more light and a blurrier background. A big one like f/11 means less light and more of the picture in focus.' },
  { term: 'Aspect ratio', cat: 'Camera', def: 'The shape of the picture: how wide it is compared to how tall. TV is 16:9. Cinema is often 2.39:1 (very wide). Phones like 9:16 (tall).' },
  { term: 'B-roll', cat: 'Camera', def: 'Extra footage that supports your main story, like shots of a city street while someone talks. It is used to cover cuts and add atmosphere.' },
  { term: 'Bokeh', cat: 'Camera', def: 'The soft, creamy blur in the out-of-focus parts of a picture, like glowing circles of light in the background.' },
  { term: 'Close-Up (CU)', cat: 'Camera', def: "A shot that frames a person's face closely. Often used to show emotion." },
  { term: 'Coverage', cat: 'Camera', def: 'Filming a scene from several angles and distances (wide, medium, close) so the editor has choices. Good coverage makes editing much easier.' },
  { term: 'Depth of field', cat: 'Camera', def: 'How much of the picture, front to back, is in focus. Shallow depth of field means only your subject is sharp. Deep means almost everything is.' },
  { term: 'Dolly', cat: 'Camera', def: 'Moving the whole camera toward or away from the subject, often on wheels or a track. Also the name of the wheeled platform.' },
  { term: 'Dutch angle', cat: 'Camera', def: 'Tilting the camera sideways so the horizon is slanted. It makes a scene feel uneasy or strange.' },
  { term: 'Establishing shot', cat: 'Camera', def: 'A wide shot at the start of a scene that shows where we are, like the outside of a building.' },
  { term: 'Exposure', cat: 'Camera', def: 'How bright or dark the picture is. Too bright is overexposed (details wash out). Too dark is underexposed (details get lost in shadow).' },
  { term: 'Eye level', cat: 'Camera', def: "A camera angle at the same height as the character's eyes. It feels natural and neutral." },
  { term: 'Focal length', cat: 'Camera', def: 'A number in millimeters (like 24mm or 85mm) that tells you how wide or zoomed in a lens is. Small numbers are wide. Big numbers are zoomed in.' },
  { term: 'Frame rate (FPS)', cat: 'Camera', def: 'How many pictures the camera takes each second. 24 is the classic movie look. 60 or more is used for smooth slow motion.' },
  { term: 'Framing', cat: 'Camera', def: 'How you place people and things inside the picture.' },
  { term: 'Gimbal', cat: 'Camera', def: 'A motorized handle that keeps the camera steady and smooth while you walk or move.' },
  { term: 'Handheld', cat: 'Camera', def: 'Holding the camera in your hands instead of using a tripod. It feels natural and a little shaky, like real life.' },
  { term: 'ISO', cat: 'Camera', def: 'How sensitive the camera is to light. A higher ISO brightens the picture in dark places but adds grainy noise.' },
  { term: 'Lens', cat: 'Camera', def: 'The glass on the front of a camera. Different lenses change how wide the picture looks and how blurry the background is.' },
  { term: 'Master shot', cat: 'Camera', def: 'A wide shot that shows the whole scene from start to finish. Closer shots are added from there.' },
  { term: 'Medium Shot (MS)', cat: 'Camera', def: 'A shot that frames a person from the waist up. Great for conversations.' },
  { term: 'Over the Shoulder (OTS)', cat: 'Camera', def: 'A shot from behind one person, looking at another. It makes conversations feel connected.' },
  { term: 'Pan', cat: 'Camera', def: 'Turning the camera left or right while it stays in the same spot, like shaking your head "no".' },
  { term: 'POV shot', cat: 'Camera', def: 'Point of view. Shows exactly what a character sees, as if the camera is their eyes.' },
  { term: 'Pull focus', cat: 'Camera', def: 'Changing what is sharp during a shot, like moving focus from a flower in front to a person behind it.' },
  { term: 'Rack focus', cat: 'Camera', def: 'Another name for pull focus: shifting sharpness from one thing to another.' },
  { term: 'Shot size', cat: 'Camera', def: 'How much of a person or place fits in the frame, from a tiny detail (extreme close-up) to a huge landscape (extreme wide).' },
  { term: 'Shutter speed', cat: 'Camera', def: 'How long the camera takes in light for each picture. A common rule for movies is to set it to double your frame rate, like 1/48 for 24 fps.' },
  { term: 'Tilt', cat: 'Camera', def: 'Pointing the camera up or down while it stays in the same spot, like nodding "yes".' },
  { term: 'Tracking shot', cat: 'Camera', def: 'A shot where the camera follows a moving person or thing.' },
  { term: 'Tripod', cat: 'Camera', def: 'A three-legged stand that holds the camera steady.' },
  { term: 'White balance', cat: 'Camera', def: 'Setting the camera so that white things look white, not orange or blue, under different kinds of light.' },
  { term: 'Wide Shot (WS)', cat: 'Camera', def: 'A shot that shows a whole person from head to toe plus the space around them.' },
  { term: 'Zoom', cat: 'Camera', def: 'Changing the lens to look closer or farther away. The camera itself does not move.' },
  { term: '180 degree rule', cat: 'Camera', def: 'A guideline that keeps characters on the same sides of the screen during a conversation. You draw an imaginary line between them and keep the camera on one side of it.' },
  { term: 'Continuity', cat: 'Camera', def: 'Keeping details the same from shot to shot, like where a coffee cup sits or how a character\'s hair looks, so the scene feels like one moment.' },

  // ----- Lighting -----
  { term: 'Bounce', cat: 'Lighting', def: 'Pointing a light at a wall or white board so the light reflects softly onto your subject.' },
  { term: 'Diffusion', cat: 'Lighting', def: 'Putting something between a light and the subject (like a sheer cloth) to make the light softer.' },
  { term: 'Fill light', cat: 'Lighting', def: 'A softer light that fills in dark shadows made by the main light.' },
  { term: 'Flag', cat: 'Lighting', def: 'A black panel used to block light from hitting a place you do not want it.' },
  { term: 'Golden hour', cat: 'Lighting', def: 'The hour after sunrise or before sunset, when sunlight is soft, warm, and beautiful.' },
  { term: 'Hard light', cat: 'Lighting', def: 'Sharp light that makes strong, crisp shadows, like direct sun.' },
  { term: 'Key light', cat: 'Lighting', def: 'The main light on your subject.' },
  { term: 'Practical', cat: 'Lighting', def: 'A light you can see in the scene, like a lamp or a candle, that actually works.' },
  { term: 'Soft light', cat: 'Lighting', def: 'Gentle light with soft shadows, like on a cloudy day.' },
  { term: 'Three-point lighting', cat: 'Lighting', def: 'A classic setup with a key light, a fill light, and a back light, which makes a person look natural and separate from the background.' },

  // ----- Sound -----
  { term: 'ADR', cat: 'Sound', def: 'Automated dialogue replacement. Actors re-record their lines in a quiet room after filming, when the original audio was not usable.' },
  { term: 'Ambient sound', cat: 'Sound', def: 'The background sound of a place, like wind, traffic, or a humming fridge.' },
  { term: 'Boom mic', cat: 'Sound', def: 'A microphone on a long pole that is held just above the actors, out of frame.' },
  { term: 'Foley', cat: 'Sound', def: 'Sound effects created by hand and added later, like footsteps or rustling clothes.' },
  { term: 'Lavalier (lav)', cat: 'Sound', def: 'A tiny microphone clipped to an actor\'s clothing.' },
  { term: 'Room tone', cat: 'Sound', def: 'About 30 seconds of the location\'s silence, recorded so editors can fill gaps smoothly.' },
  { term: 'Wild track', cat: 'Sound', def: 'Audio recorded without picture, such as a sound effect or room tone.' },

  // ----- Script -----
  { term: 'Action', cat: 'Script', def: 'The lines in a screenplay that describe what we see and hear, written in the present tense.' },
  { term: 'Beat', cat: 'Script', def: 'A small moment in a scene where something shifts, or a short pause in dialogue.' },
  { term: 'Character cue', cat: 'Script', def: 'The character name in capital letters just above their dialogue.' },
  { term: 'Dialogue', cat: 'Script', def: 'The words characters say out loud.' },
  { term: 'EXT. / INT.', cat: 'Script', def: 'Short for exterior (outside) and interior (inside). They start every scene heading.' },
  { term: 'O.S. / V.O.', cat: 'Script', def: 'Off screen (we hear a character who is in the scene but not in the picture) and voice over (a voice like a narrator that is not in the scene).' },
  { term: 'Parenthetical', cat: 'Script', def: 'A short note in brackets under a character name about how a line is said, like (whispering).' },
  { term: 'Scene heading', cat: 'Script', def: 'The line that starts every scene and tells where and when it happens, like INT. KITCHEN - NIGHT. Also called a slugline.' },
  { term: 'Screenplay', cat: 'Script', def: 'The written script for a film, in a special format where one page is about one minute of screen time.' },
  { term: 'Slugline', cat: 'Script', def: 'Another name for a scene heading.' },
  { term: 'Transition', cat: 'Script', def: 'A note about how one scene moves into the next, like CUT TO: or FADE OUT.' },

  // ----- Editing -----
  { term: 'Color grading', cat: 'Editing', def: 'Adjusting colors in editing to set the mood, like warm and golden or cold and blue.' },
  { term: 'Cut', cat: 'Editing', def: 'The moment one shot changes to another. "Cut!" is also what the director says to stop filming.' },
  { term: 'Dissolve', cat: 'Editing', def: 'A transition where one shot slowly fades into the next.' },
  { term: 'Jump cut', cat: 'Editing', def: 'A cut between two shots of the same thing that feels like time suddenly skipped.' },
  { term: 'Montage', cat: 'Editing', def: 'A series of short shots joined together to show time passing or a lot of information quickly.' },
  { term: 'Picture lock', cat: 'Editing', def: 'The point when the edit is final, so sound and music can be finished without things moving around.' },
  { term: 'Rough cut', cat: 'Editing', def: 'A first, unpolished version of the edit with the story in place.' },

  // ----- Crew -----
  { term: '1st AC', cat: 'Crew', def: 'First assistant camera. Keeps the picture in focus and takes care of the camera and lenses.' },
  { term: 'Boom operator', cat: 'Crew', def: 'The person who holds the boom microphone over the actors.' },
  { term: 'Cinematographer (DP)', cat: 'Crew', def: 'The director of photography. In charge of how the film looks: the camera, the lighting, and the framing.' },
  { term: 'Director', cat: 'Crew', def: 'The person who guides the story and the performances, and makes the creative decisions.' },
  { term: 'Gaffer', cat: 'Crew', def: 'The head of the lighting team.' },
  { term: 'Grip', cat: 'Crew', def: 'A crew member who handles the equipment that supports the camera and lights, like stands and dollies.' },
  { term: 'Producer', cat: 'Crew', def: 'The person who makes the film happen: money, schedule, people, and logistics.' },
  { term: 'Production designer', cat: 'Crew', def: 'In charge of the look of the sets, props, and locations.' },
  { term: 'Script supervisor', cat: 'Crew', def: 'Tracks continuity and keeps notes on every take so the editor knows what was filmed.' },
  { term: 'Sound mixer', cat: 'Crew', def: 'The person who records the audio on set.' },

  // ----- Production -----
  { term: 'Breakdown', cat: 'Production', def: 'Going through a script scene by scene and listing everything needed, like props, costumes, and locations.' },
  { term: 'Call sheet', cat: 'Production', def: 'A one-page plan for a shoot day. It lists where to go, what time to arrive, who is needed, and what is being filmed.' },
  { term: 'Call time', cat: 'Production', def: 'The time a person needs to arrive on set.' },
  { term: 'Location scout', cat: 'Production', def: 'Visiting places in advance to decide whether they are right for filming.' },
  { term: 'Pre-production', cat: 'Production', def: 'Everything you do before filming: writing, planning, casting, scheduling, and scouting.' },
  { term: 'Post-production', cat: 'Production', def: 'Everything after filming: editing, sound, color, and music.' },
  { term: 'Production schedule', cat: 'Production', def: 'The plan for which scenes you film on which day.' },
  { term: 'Shot list', cat: 'Production', def: 'A checklist of every shot you plan to film, in the order you want to film them.' },
  { term: 'Slate (clapperboard)', cat: 'Production', def: 'A board shown at the start of each take with the scene, shot, and take number, so editors can find the right footage. The clap helps sync sound to picture.' },
  { term: 'Storyboard', cat: 'Production', def: 'A series of pictures that shows how each shot will look before you film it.' },
  { term: 'Take', cat: 'Production', def: 'One attempt at filming a shot. You often film several takes to get the best one.' },
  { term: 'Wrap', cat: 'Production', def: 'Finishing filming for the day, or for the entire film.' },
]
