// Short, practical guides. Block types: p (paragraph), h (heading), list, steps, tip, visual, link.
export const ARTICLES = [
  {
    slug: 'format-a-screenplay',
    title: 'How to Format a Screenplay',
    blurb: 'The five kinds of lines in a script, and how to write them so they look professional.',
    minutes: 4,
    tone: 'pink',
    body: [
      { t: 'p', text: 'A screenplay looks different from a story or an essay. It follows a standard format so everyone on a film can read it the same way. The good news: there are only a few kinds of lines to learn.' },
      { t: 'visual', name: 'screenplay' },
      { t: 'h', text: 'The kinds of lines' },
      { t: 'list', items: [
        'Scene heading: where and when the scene happens. Start with INT. (inside) or EXT. (outside), then the place, a dash, and the time of day. Example: INT. KITCHEN - NIGHT.',
        'Action: what we see and hear, written in the present tense. "Maya opens the fridge," not "Maya opened the fridge."',
        'Character: the name of the person about to speak, in capital letters.',
        'Dialogue: the words they say, right under their name.',
        'Parenthetical: a very short note about how a line is said, like (whispering). Use it rarely.',
      ] },
      { t: 'h', text: 'One page is about one minute' },
      { t: 'p', text: 'The format is designed so that one page of script is roughly one minute on screen. That is why a 10 page script makes a 10 minute short film.' },
      { t: 'tip', text: 'Write only what the audience can see or hear. Instead of "Maya feels nervous," write "Maya checks her phone three times in ten seconds."' },
      { t: 'p', text: 'You do not have to remember any of this while writing. In TakeTwo PrePro, press Enter to move to the next kind of line and Tab to change it. The spacing takes care of itself.' },
      { t: 'link', to: '/projects', label: 'Open your projects' },
    ],
  },
  {
    slug: 'make-a-shot-list',
    title: 'How to Make a Shot List',
    blurb: 'A checklist of every shot you plan to film, so you never forget one on shoot day.',
    minutes: 4,
    tone: 'blue',
    body: [
      { t: 'p', text: 'A shot list is a simple checklist of every shot you want to film. On set, it keeps you focused. You always know what is done and what is left.' },
      { t: 'visual', name: 'shotlist' },
      { t: 'h', text: 'How to make one' },
      { t: 'steps', items: [
        'Read each scene and imagine how you will film it. Where will the camera go?',
        'List the shots, starting with a wide shot that shows the whole scene (a master shot).',
        'Add closer shots for important moments: medium shots for conversations, close-ups for emotion.',
        'Write down the details that matter: shot size, lens, camera, and any notes.',
        'Guess how long each shot will take, including setup. Be generous.',
        'Put the shots in the order you will film them, not the order of the script.',
      ] },
      { t: 'tip', text: 'Shoot everything that is set up the same way together. Filming all the shots on one side of a conversation before moving the camera saves a lot of time.' },
      { t: 'p', text: 'Give each shot a number that includes its scene, like 4B for the second shot in scene 4. It makes talking on set quick and clear.' },
      { t: 'link', to: '/tools/shot-sizes', label: 'See every shot size explained' },
    ],
  },
  {
    slug: 'storyboard',
    title: 'How to Storyboard',
    blurb: 'Plan your shots as pictures. No drawing skills needed.',
    minutes: 3,
    tone: 'violet',
    body: [
      { t: 'p', text: 'A storyboard is a row of pictures that shows how each shot will look before you film it. It is one of the best ways to find problems early, when they are still easy to fix.' },
      { t: 'visual', name: 'sketch' },
      { t: 'h', text: 'You do not need to draw well' },
      { t: 'p', text: 'Stick figures and boxes are perfect. What matters is where people and things are in the frame. If you really do not want to draw, use photos. Stand where the camera would be and snap a picture with your phone.' },
      { t: 'steps', items: [
        'Draw a rectangle in the shape of your film (like 16:9).',
        'Sketch the main person or object where they will be in the frame.',
        'Write a short note under it: shot size, what happens, and any dialogue.',
        'Use an arrow to show if a person or the camera moves.',
        'Make a new frame each time the camera angle changes.',
      ] },
      { t: 'tip', text: 'Do not try to make it pretty. A messy storyboard that you finish beats a beautiful one that you never do.' },
      { t: 'link', to: '/projects', label: 'Start a storyboard in a project' },
    ],
  },
  {
    slug: 'shot-sizes',
    title: 'Understanding Shot Sizes',
    blurb: 'How close the camera is changes how the audience feels. Learn the main sizes.',
    minutes: 3,
    tone: 'teal',
    body: [
      { t: 'p', text: 'A shot size is how much of a person or place fits in the frame. Moving closer or farther changes the feeling of a scene.' },
      { t: 'visual', name: 'shot-strip' },
      { t: 'h', text: 'The main ones' },
      { t: 'list', items: [
        'Wide shot: shows the whole person and the place around them. It tells us where we are.',
        'Medium shot: from about the waist up. This is the shot for conversations.',
        'Close-up: a face filling the frame. It shows what someone is feeling.',
        'Extreme close-up: one small detail, like eyes or a hand.',
      ] },
      { t: 'h', text: 'A simple rule' },
      { t: 'p', text: 'Go wider to show where something happens. Go closer to show how it feels. Most scenes start wide, move to medium for the talking, and use close-ups for the big moments.' },
      { t: 'tip', text: 'Save close-ups for what matters most. If every shot is a close-up, none of them feels special.' },
      { t: 'link', to: '/tools/shot-sizes', label: 'Open the shot size guide' },
    ],
  },
  {
    slug: 'camera-angles',
    title: 'Camera Angles Explained',
    blurb: 'Where you put the camera tells the audience how to feel about a character.',
    minutes: 3,
    tone: 'amber',
    body: [
      { t: 'p', text: 'The camera angle is how high or low the camera sits compared to what it is filming. Even a small change affects how a character feels.' },
      { t: 'visual', name: 'angles' },
      { t: 'list', items: [
        'Eye level: natural and neutral. This is your default.',
        'High angle: the camera looks down. The person can seem small, weak, or trapped.',
        'Low angle: the camera looks up. The person can seem powerful, tall, or scary.',
        'Dutch angle: the camera is tilted sideways. It makes a scene feel uneasy.',
        'Overhead: straight down from above. Good for maps, tables, and a "god\'s eye" view.',
      ] },
      { t: 'tip', text: 'Think about how you want the audience to feel about the person in the shot. Then pick the angle that matches that feeling.' },
      { t: 'p', text: 'You can mix and match. A low angle on the villain and an eye level shot on the hero tells the audience who is in control, without a single line of dialogue.' },
    ],
  },
  {
    slug: 'make-a-call-sheet',
    title: 'How to Make a Call Sheet',
    blurb: 'The one-page plan that tells everyone where to be and when.',
    minutes: 4,
    tone: 'rose',
    body: [
      { t: 'p', text: 'A call sheet is a one-page plan for a shoot day. Everyone gets one, usually the day before. It answers the questions people ask most: where do I go, when do I arrive, and what are we filming?' },
      { t: 'visual', name: 'callsheet' },
      { t: 'h', text: 'What goes on it' },
      { t: 'list', items: [
        'The film title, the date, and which shoot day it is.',
        'The general call time, when most people should arrive.',
        'The location and address, with parking and directions.',
        'The schedule: which scenes you will film, in what order, and roughly when.',
        'The cast and crew who are needed, with their own call times and phone numbers.',
        'Equipment, notes, and safety information, like the nearest hospital.',
      ] },
      { t: 'tip', text: 'Give cast and crew different call times. An actor who is not needed until noon should not wait around from 7 AM.' },
      { t: 'p', text: 'In TakeTwo PrePro, a call sheet builds itself from your schedule, cast, crew, and equipment. You only change what is special about that day, then print it or save it as a PDF.' },
    ],
  },
  {
    slug: 'plan-a-shoot',
    title: 'How to Plan a Shoot',
    blurb: 'From finished script to ready for day one, in the order that makes sense.',
    minutes: 5,
    tone: 'violet',
    body: [
      { t: 'p', text: 'Planning is the secret of a smooth shoot. Every hour you spend planning saves several hours on set. Here is a simple order to work in.' },
      { t: 'visual', name: 'timeline' },
      { t: 'steps', items: [
        'Break down your script. List the characters, locations, props, and costumes in every scene.',
        'Find locations. Visit them, take photos, and ask permission. Note parking, power, and noise.',
        'Cast your actors and find your crew. Ask when they are free.',
        'Make a shot list and storyboard so you know what to film.',
        'Build the schedule. Group scenes by location, and by who is needed, to save time.',
        'Make a gear checklist. Check batteries, memory cards, and lights the day before.',
        'Send the call sheet to everyone the day before.',
      ] },
      { t: 'tip', text: 'Plan for things to take longer than you think. A good rule of thumb is to add an extra hour to every shoot day, and to never schedule more than you can finish.' },
      { t: 'p', text: 'And have a plan for bad weather, a late actor, or a dead battery. Having a backup for the most important scenes makes you calm when something goes wrong.' },
      { t: 'link', to: '/tools/storage', label: 'Work out how much storage you need' },
    ],
  },
  {
    slug: 'crew-roles',
    title: 'Basic Film Crew Roles',
    blurb: 'Who does what on a film set, in plain language.',
    minutes: 4,
    tone: 'teal',
    body: [
      { t: 'p', text: 'Big movies have hundreds of crew members. A small student film might have five people. Even so, the same jobs need to get done. Here are the main ones.' },
      { t: 'visual', name: 'crew' },
      { t: 'tip', text: 'On small shoots, one person often has several jobs. A director might also be the producer, and the camera operator might also be the editor. That is completely normal.' },
      { t: 'p', text: 'When you build your crew, start with these four roles. If someone is covering each one, you can make a film: someone to lead the story, someone to run the camera, someone to record sound, and someone to keep everything organized.' },
      { t: 'link', to: '/tools/glossary', label: 'Look up a film term' },
    ],
  },
  {
    slug: 'continuity',
    title: 'Continuity Basics',
    blurb: 'Keeping details the same from shot to shot, so scenes feel real.',
    minutes: 3,
    tone: 'amber',
    body: [
      { t: 'p', text: 'You rarely film a scene in one go. You film it in pieces, from different angles, over an hour or more. When the pieces are edited together, everything needs to match. That is continuity.' },
      { t: 'visual', name: 'continuity' },
      { t: 'h', text: 'What to watch' },
      { t: 'list', items: [
        'Props: where is the cup, and is it full or empty?',
        'Wardrobe: sleeves rolled up? Jacket zipped?',
        'Hair and makeup: how messy is it supposed to be at this point?',
        'Position: which hand is holding the phone? Where is each person standing?',
        'Direction: if someone walks left to right, they should keep going that way in the next shot.',
      ] },
      { t: 'tip', text: 'Take a quick photo on your phone after each shot. It is the easiest continuity record there is. In On-Set Mode, you can also type a continuity note for each take.' },
      { t: 'p', text: 'The person who tracks all this is called the script supervisor. On a small film, it is often an assistant or whoever is free. Just make sure someone is watching.' },
    ],
  },
  {
    slug: 'rule-180',
    title: 'The 180 Degree Rule',
    blurb: 'A simple guideline that keeps conversations easy to follow.',
    minutes: 3,
    tone: 'pink',
    body: [
      { t: 'p', text: 'When two people talk, one is usually on the left of the screen and one on the right. If the camera jumps to the other side between shots, they seem to swap places, and the audience gets confused. The 180 degree rule prevents this.' },
      { t: 'visual', name: 'rule180' },
      { t: 'h', text: 'How it works' },
      { t: 'steps', items: [
        'Imagine a line running between the two people. This is the line of action.',
        'Put your camera on only one side of that line for the whole scene.',
        'Every shot from that side keeps person A on the left and person B on the right.',
      ] },
      { t: 'h', text: 'When can you break it?' },
      { t: 'p', text: 'It is a guideline, not a law. Filmmakers cross the line on purpose to create confusion, or smoothly by showing the camera moving across it, or by cutting to a neutral shot (one straight down the line) in between.' },
      { t: 'tip', text: 'Planning your shots on a storyboard makes it much easier to spot where the camera is, and to keep it on the right side.' },
    ],
  },
]

export const articleBySlug = (slug) => ARTICLES.find((a) => a.slug === slug)
